server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: xc_cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0

eureka:
  client:
    register-with-eureka: true #是否将自己注册到eureka服务器中
    fetch-registry: true #服务发现,是否从eureka中获取注册信息
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/,http://eureka01:50101/eureka/}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: warn