server:
  port: 9999
spring:
  application:
    name: test-mybatis
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springtest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sjr.model

#showSql
logging:
  level:
    com:
      sjr:
        dao : debug